import type { Metadata } from "next";
import { Poppins, Inter, Damion } from "next/font/google";
import "./globals.css";

const titleFont = Damion({ weight: "400", variable: "--font-title" });
const subtitleFont = Poppins({ subsets: ["latin"], weight: "500", variable: "--font-subtitle" });
const bodyFont = Inter({ subsets: ["latin"], variable: "--font-body" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bodyFont.variable} ${titleFont.variable} ${subtitleFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
